### ISSUE TITLE
Expand Button

### ISSUE THREAD

**Issue by mberiam** [BasicPrimitives/javascript#16]
I have included a button in the bottom of each box (node) of the diagram, which fires an event and loads children nodes, growing my tree dynamically. So far, no big deal. The problem started when I have updated basic primitives lib and the button now is not fully clickable. Its area seems to receive the click and the button changes its color when I click it, showing it was clicked, but no click event raises. When I click right on its middle, it works. I have tried lots of things, including changing it z-index, with no results. Any ideas? I do not want to downgrade my lib. I think it should work using the new version. TIA

**Comment by BasicPrimitives** [comment]
What framework do you use jQuery or JavaScript API? I'll make working sample for you.

**Comment by mberiam** [comment]
jQuery.
Thanks!

Em seg, 26 de ago de 2019 10:28, Basic Primitives Inc <
notifications@github.com> escreveu:

**Comment by BasicPrimitives** [comment]
![image](https://user-images.githubusercontent.com/2230139/64022278-d4f9ec80-cb03-11e9-8568-0ab1ba9a6eb8.png)
Save attached file for samples code, you need to download it and place into our jQuery samples folder in order to match references to packages.
[buttonsintemplate.pdf](https://github.com/BasicPrimitives/javascript/files/3559994/buttonsintemplate.pdf)
