### ISSUE TITLE
"2 level" org chart

### ISSUE THREAD

**Issue by xosevilla** [BasicPrimitives/javascript#22]
Hi,
Is it possible to build a structure as on screen?
![sample](https://user-images.githubusercontent.com/16478215/65943720-d9822f80-e438-11e9-8ceb-4a23bb5e7330.jpg)

The main issue is to move child companies to the level down just after "company 1" contacts (as on-screen).
Thanks.

**Comment by BasicPrimitives** [comment]
Hi XosevillaLook at invisible nodes examplehttps://www.basicprimitives.com/usecases/customlayoutwithinvisibleitemsYou need to create couple of invisible nodes for your Company 1, set vertical children layout for Company1Then set horizontal children layout for the first invisible node and add Company 1 logical children to it.Then set horizontal children layout for the second invisible node and add Company 1 child company nodes to itIt should workBest regardsAndreyBP
-------- Original message --------From: xosevilla <notifications@github.com> Date: 2019-10-01  3:53 AM  (GMT-05:00) To: BasicPrimitives/javascript <javascript@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [BasicPrimitives/javascript] "2 level" org chart (#22) Hi,
Is it possible to build a structure as on screen?

The main issue is to move child companies to the level down just after "company 1" contacts (as on-screen).
Thanks.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BasicPrimitives/javascript/issues/22?email_source=notifications\u0026email_token=AARAO63TAUMIE7D5VS3AAJ3QML6XBA5CNFSM4I4FZAF2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HOYO5SA",
"url": "https://github.com/BasicPrimitives/javascript/issues/22?email_source=notifications\u0026email_token=AARAO63TAUMIE7D5VS3AAJ3QML6XBA5CNFSM4I4FZAF2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HOYO5SA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by xosevilla** [comment]
That's what i looking for.
Thanks!
