### ISSUE TITLE
Vertical alignment of children in Family Chart

### ISSUE THREAD

**Issue by khalilTN** [BasicPrimitives/javascript#23]
Hi,

Can we have vertically organized children in family chart.
In docs, the option childrenPlacementType in itemConfig can be found only in Organizational Charts.

Thank you.

**Comment by BasicPrimitives** [comment]
Family chart supports matrixed nodes layout: https://www.basicprimitives.com/usecases/familyconnectorsvisualizationIf you set maximum matrix width  maximumColumnsInMatrix to 1 you will get column layout of the nodes.Matrixes work only for nodes having the same set of children and parents.Matrix layout is enabled globally for all diagram nodes.
-------- Original message --------From: KhalilTN <notifications@github.com> Date: 2019-11-08  8:39 AM  (GMT-05:00) To: BasicPrimitives/javascript <javascript@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [BasicPrimitives/javascript] Vertical alignment of children in
  Family Chart (#23) Hi,
Can we have vertically organized children in family chart.
In docs, the option childrenPlacementType in itemConfig can be found only in Organizational Charts.
Thank you.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BasicPrimitives/javascript/issues/23?email_source=notifications\u0026email_token=AARAO6Y3YL427N5LYZZGMGTQSVT2HA5CNFSM4JKXLWP2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HX64CMA",
"url": "https://github.com/BasicPrimitives/javascript/issues/23?email_source=notifications\u0026email_token=AARAO6Y3YL427N5LYZZGMGTQSVT2HA5CNFSM4JKXLWP2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HX64CMA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by khalilTN** [comment]
As i understand, i can't have vertical alignment for children of a determined item, vertical alignment have to be applied to the whole organigram.
Is this correct ?

**Comment by BasicPrimitives** [comment]
Please, draw picture of how you want nodes to be placed. Every child can be under control of multiple parents. So setting children formation at parent is wrong. We can add extra property like useMatrixFormation for actual child node, so that way API is going to be deterministic.
-------- Original message --------From: KhalilTN <notifications@github.com> Date: 2019-11-08  10:37 AM  (GMT-05:00) To: BasicPrimitives/javascript <javascript@noreply.github.com> Cc: Basic Primitives Info <info@basicprimitives.com>, Comment <comment@noreply.github.com> Subject: Re: [BasicPrimitives/javascript] Vertical alignment of children in
  Family Chart (#23) As i understand, i can't have vertical alignment for children of a determined item, vertical alignment have to be applied to the whole organigram.
Is this correct ?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BasicPrimitives/javascript/issues/23?email_source=notifications\u0026email_token=AARAO66VWOTLG2S6FCDKJEDQSWBUXA5CNFSM4JKXLWP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDSPGBA#issuecomment-551875332",
"url": "https://github.com/BasicPrimitives/javascript/issues/23?email_source=notifications\u0026email_token=AARAO66VWOTLG2S6FCDKJEDQSWBUXA5CNFSM4JKXLWP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDSPGBA#issuecomment-551875332",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by khalilTN** [comment]
![image](https://user-images.githubusercontent.com/9549132/68490770-e79e4980-0249-11ea-974a-ac626a552758.png)

Actually, i seek to create this shape.
I need multip parent relations also, that's why i'm not using Organizational Charts

**Comment by BasicPrimitives** [comment]
Please, remove any personal information from layout and send picture directly to support@basicprimitives.com
-------- Original message --------From: KhalilTN <notifications@github.com> Date: 2019-11-08  11:06 AM  (GMT-05:00) To: BasicPrimitives/javascript <javascript@noreply.github.com> Cc: Basic Primitives Info <info@basicprimitives.com>, Comment <comment@noreply.github.com> Subject: Re: [BasicPrimitives/javascript] Vertical alignment of children in
  Family Chart (#23) 
Actually, i seek to create this shape.
I need multip parent relations also, that's why i'm not using Organizational Charts

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BasicPrimitives/javascript/issues/23?email_source=notifications\u0026email_token=AARAO62TLFB27HXEHPDGIWTQSWFA7A5CNFSM4JKXLWP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDSSAMI#issuecomment-551886897",
"url": "https://github.com/BasicPrimitives/javascript/issues/23?email_source=notifications\u0026email_token=AARAO62TLFB27HXEHPDGIWTQSWFA7A5CNFSM4JKXLWP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDSSAMI#issuecomment-551886897",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by khalilTN** [comment]
I have updated the previous picture.
This is the whole diagram i seek to be able to create.
[Copie de 2019 06 30 Organigramme Groupe BMF - logiciel.pdf](https://github.com/BasicPrimitives/javascript/files/3830085/Copie.de.2019.06.30.Organigramme.Groupe.BMF.-.logiciel.pdf)

**Comment by BasicPrimitives** [comment]
Why do you connect parents and kids via the same side of rectangle? 

In order to understand whether connection line goes to parents or kids your diagram forces users to visually trace its destination. If diagram consistent in how sides of nodes are being used then it gives you clear indication of parent/child relation type.

**Comment by BasicPrimitives** [comment]
What is the logic to place the "greenish" node at 3d row? 

If roots are equal they are supposed to be ether at the very first row or they should be placed at the row of its immediate children.

**Comment by BasicPrimitives** [comment]
In the 4th column you have vertical line going across one of the child nodes. Is it on purpose? What does it mean?

**Comment by BasicPrimitives** [comment]
In columns connection lines between parent and children are placed to the left and right sides. Do you have any rule for that?

**Comment by BasicPrimitives** [comment]
Why do you place first node of the first column at the 5th row? First column does not share the same parents with other columns?

**Comment by khalilTN** [comment]
> Why do you connect parents and kids via the same side of rectangle?
> 
> In order to understand whether connection line goes to parents or kids your diagram forces users to visually trace its destination. If diagram consistent in how sides of nodes are being used then it gives you clear indication of parent/child relation type.

If it's not possible to place that node like that, we can try another position.
Positioning that node like that is not mandatory

**Comment by khalilTN** [comment]
> What is the logic to place the "greenish" node at 3d row?
> 
> If roots are equal they are supposed to be ether at the very first row or they should be placed at the row of its immediate children.

If it's not possible to place that node like that, we can try another position.
Positioning that node like that is not mandatory

**Comment by khalilTN** [comment]
> In the 4th column you have vertical line going across one of the child nodes. Is it on purpose? What does it mean?

No it's not, they where overlapped due the child being aligned to the right

**Comment by khalilTN** [comment]
> In columns connection lines between parent and children are placed to the left and right sides. Do you have any rule for that?

No, we do not have any rule for that, if having vertical standard links, user can mistakenly think that the node on top of that child is the parent, while in reality, both are children of the same parent.

**Comment by khalilTN** [comment]
> Why do you place first node of the first column at the 5th row? First column does not share the same parents with other columns?

That three nodes belong to the same category of the nodes filled in white (the bottom of the organigram), it's not mandatory to have them in that position

**Comment by khalilTN** [comment]
> Why do you connect parents and kids via the same side of rectangle?
> 
> In order to understand whether connection line goes to parents or kids your diagram forces users to visually trace its destination. If diagram consistent in how sides of nodes are being used then it gives you clear indication of parent/child relation type.

Can you clarify the question ? (Thank you for your support :))

**Comment by BasicPrimitives** [comment]
> > Why do you connect parents and kids via the same side of rectangle?
> > In order to understand whether connection line goes to parents or kids your diagram forces users to visually trace its destination. If diagram consistent in how sides of nodes are being used then it gives you clear indication of parent/child relation type.
> 
> Can you clarify the question ? (Thank you for your support :))
You are making a regular centered, top to bottom drawn diagram.

So if you look at a single node it is good when it's parents are connected to the top side of the node and it's children to its bottom side. Side connection indicates equal relations like assistant or adviser relation.

**Comment by khalilTN** [comment]
> > > Why do you connect parents and kids via the same side of rectangle?
> > > In order to understand whether connection line goes to parents or kids your diagram forces users to visually trace its destination. If diagram consistent in how sides of nodes are being used then it gives you clear indication of parent/child relation type.
> > 
> > 
> > Can you clarify the question ? (Thank you for your support :))
> > You are making a regular centered, top to bottom drawn diagram.
> 
> So if you look at a single node it is good when it's parents are connected to the top side of the node and it's children to its bottom side. Side connection indicates equal relations like assistant or adviser relation.

Having side connection will prevent user from mistakenly thinking that the vertically ordered nodes are nested parent/child (every node is the parent of the node under it). Nodes sorted vertically with side connections belong to the same layer and have the same parents

**Comment by BasicPrimitives** [comment]
I see. You need diagram layout to match your holding structure and at the same time you need to show business ownership relations. In general ownership relations matches holding structure that is why you are trying to keep it.

**Comment by khalilTN** [comment]
What is important to us is to have third layer (nodes in white) being sorted in vertically even if they have children, it would be helpful for us to decide childrenPlacementType in parent nodes.
In that case, we may have horizontal childrenPlacementType in layer 1, 2, 3 and vertical childrenPlacementType in layer 4, for layer 5 (nodes in white) it will be horizontal

**Comment by BasicPrimitives** [comment]
What is your primary objective? Do you need to have PDF file having all the data displayed or you are building UI application for ad-hoc data analysis?

**Comment by BasicPrimitives** [comment]
Your diagram is relatively small, the question is how many such diagrams you have. If you need visual data analysis tool to for your relations, I would recommend to hide as many relations as possible, because they would mass up your screen. Display only minimal relations to show your dependencies between nodes and then use annotations to highlight business ownership relations between individual nodes.

The diagram without direct grand parents relations would be lightweight and easy to trace dependencies.

The nodes will contain info about number of parents. The on screen annotations will show business ownership  relations as a straight lines, so your users would not need to trace links.

We can make a small demo for you of how it would looks like in famDiagram.

**Comment by BasicPrimitives** [comment]
Your diagram layout and nodes positions reflect corporate structure, but connections reflect business ownership between them. The following is example of org structure with annotations showing business ownership relations:

If you like this approach we can improve labels placement so they would match connections lines.

![image](https://user-images.githubusercontent.com/2230139/69238753-bc2f2f00-0b66-11ea-8699-97b60cc987e8.png)
