### ISSUE TITLE
Are you planning to make a typescript version of the BasicPrimitive package?

### ISSUE THREAD

**Issue by User195** [BasicPrimitives/javascript#27]
Hi, are you planning to make a typescript version of the BasicPrimitive package?

**Comment by BasicPrimitives** [comment]
What would you like to see in our product? New features like: flow visualization, axes for levels, new layouts, native implementation for mobile or just translated code from JavaScript to TypeScript? Why do you ask for TypeScript? Do you need TypeScript API only or you want to see the whole code base in TypeScript?

**Comment by User195** [comment]
this "just translated code from JavaScript to TypeScript"
"TypeScript API only"
I already use typescript in my project and I want to import your react components.

**Comment by BasicPrimitives** [comment]
So you need TypeScript version of our API. Am I right? Do you have any open source React component in mind which support TypeScriptabd you like to use?

**Comment by User195** [comment]
Yes, you understood me right. 
I recently used Material-ui, they support Typescript

**Comment by saurabh47** [comment]
@BasicPrimitives 
**Support for Angular2+**
Is there any documentation of basic primitive for Angular2+?
(I am able to use a basic primitive library in angular 8 projects. but I have not found any official  documentation.)

**Comment by BasicPrimitives** [comment]
We have no samples for latest Angular framework.

**Comment by mangesh236** [comment]
Is there is basic primitive for angular 2 like we saw basic primitive for react like wrapper?
Along with drag n drop functionality.

**Comment by BasicPrimitives** [comment]
We render our product site in React, see `react-demo` repository. It is impossible to implement React Drag & Drop library support with JavaScript controls directly manipulating DOM. That is why we created `basicprimitives-react` library for our site.

**Comment by mangesh236** [comment]
> We render our product site in React, see `react-demo` repository. It is impossible to implement React Drag & Drop library support with JavaScript controls directly manipulating DOM. That is why we created `basicprimitives-react` library for our site.

Have any plan to create basicprimitive-angular library ?

**Comment by BasicPrimitives** [comment]
In order to make decision you need Angular-2 implementation within couple of weeks. We can start work on it on 3d week of April. Taking into account React implementation experience and the fact that source code is ready for that, it should take 2-3 weeks of our time. So our estimate is mid May. Does it work for you? Otherwise we would rather focus on further core features upgrades.

**Comment by luchmewep** [comment]
Hello, so this is a similar issue I submitted yesterday. I am also wondering the same thing: if you have a Typescript support. Typescript has become a standard for bigger organizations due to how predictable Javascript has become. With just a single ctrl+space, I now know what functions or props or stuff I can get from any of the package. It's something that compliments your docs so that even when offline, we know what a certain function can do or what data type it will return.

I hope you will have a TS support soon. I wish you all the best. 👍

**Comment by BasicPrimitives** [comment]
Our product is being developed in [ECMAScript® 2015 Language Specification](http://www.ecma-international.org/ecma-262/6.0/)
