### ISSUE TITLE
Manual control over minimized/maximized items (for each item)

### ISSUE THREAD

**Issue by pmirek** [BasicPrimitives/javascript#28]
Hi,

Can you consider improvement like control of size(maximized/minimized) per one item only?
Now functionality for primitives.common.PageFitMode.FitToPage is like you have a group of minimized items set automatically. Then in many cases you get many of items maximized, when picking one of particular thing of your interest.
I think about smth like having event handler for onClick or onDoubleClik, that toggles maximized/minimized state available for each item.
Also it would be great if you can pick if you want to start with all items minimized.
If this behaviour is already available, can you please advice how this can be achieved with an example piece of code?

Thanks!

**Comment by BasicPrimitives** [comment]
In order to show all nodes minimized you have to:
- create large diagram bigger than your screen
- set cursorItem to null
- set selectedItems to []

[all_markers.pdf](https://github.com/BasicPrimitives/javascript/files/4064976/all_markers.pdf)

**Comment by BasicPrimitives** [comment]
In order to control visibility of individual nodes use selectedItems collection
- Add nodes you need to show full size into it
- Hide selection checkboxes, set options.hasSelectorCheckbox = primitives.common.Enabled.False;
![image](https://user-images.githubusercontent.com/2230139/72436174-d1db6200-376d-11ea-8351-b03c0562e11f.png)

Pay attention that control has paired events:
onCursorChanging
onCursorChanged
https://www.basicprimitives.com/usecases/selectingcursoritem

You have to update your selectedItems in onCursorChanging event, so new set of selected maximized items would be visible right after the click
