### ISSUE TITLE
Fam Diagram, Label Annotation on Spouse Connections

### ISSUE THREAD

**Issue by paul-v-g** [BasicPrimitives/javascript#37]
Hi, 
Adding a LabelAnnotion to a spouse connection currently doesn't seem to work. Whereas HighlightPathAnnotation, for example, does.

Is this by design?
Or is it a featurre you might be willing to implement?

Thanks

**Comment by BasicPrimitives** [comment]
Hi, spouse relations create hidden marriage nodes, we suggest to create marriage nodes  explicitly in the diagram, it will make your diagram more clear and most likely you would need to create Annotations, since your marriage node would be that annotation.
We din't plan to evolve spouse connections, they are subject for  deprication. See family diagram demos we created in javascript and react-demos repositories. They have acceptable design for practical  usage.
