### ISSUE TITLE
Complements + feature request (Typescript & connectors click)

### ISSUE THREAD

**Issue by DutchKevv** [BasicPrimitives/javascript#38]
Hi there,

first of all, great work! We have been looking for some time, and this one does it really well :) So thanks for that!

Before we buy (and make pull requests...), a few questions:

- Will there be typescript definitions? This would make developing a lot easier!
    - if we make a pull request for types.d.ts, will you include it? 
- Can we make connectors  / annotations clickable? 
    - in our usecase, we want to show a popup so the 'amount' can be set / changed of how much one node owns of the child / parent node. Like ----->40%------>, where 40% is configurable by UI when clicking on the connected lines
- We use a lot of Angular, how do you feel about making a special ng-basic-primitives package?
  - if we make a pull request for it, will you include it? 
- It doesn't work really well now with typescript / esnext modules ... Tree-shaking isn't possible at all it seems... Making it a > 1MB (minimized, heavy) dep... Any plans for refactoring?
    -  if we make a pull request for it, will you include it? 

Thanks

**Comment by BasicPrimitives** [comment]
Will there be typescript definitions? This would make developing a lot easier!
if we make a pull request for types.d.ts, will you include it?
Look, there is no simple answer, it is definitely good feature for TypeScript developers, but so far we don't use TypeScript in our project and don't plan to use it in the future. 

TypeScript it is legacy of OOP and single threaded windows based development practices, the best usage OOP found in development of Windows GUI components. The OOP stays popular only because of huge developer base adopted it long time ago. Many systems ware influenced without any reason by OOP development practices, so we still have a huge legacy of OOP developers and systems developed by them. If you look at contemporary systems there is no such thing as Object anymore, we work with structures deprived of any encapsulation and state management. So if you look at our code base we spent significant efforts to refactor objects towards stateless immutable design, we still have a lot of OOP in our project, but we found that pure functions are way more easier to write and test. Work with structures makes project easier to understand and maintain, project's performance becomes better. Code maintenance easier. So we already made our choice to go into functional development paradigm.  TypeScript brings old school development practices and the only way to get rid of OOP legacy is to avoid usage of Classes in the system. Take a look at Software Development industry in general and what happen to it in the recent 20 years. All software development market leaders  adopted distributed system design, unitizing parallel data processing, the main problem of parallelism it is state management, if you manage state you manage synchronization and locking, locking kills concurrency. So OOP kills distributed systems, it is a paradigm created to work with single thread applications having no concurrency to manage object state. So coming back to TypeScript, it is legacy of OOP. It is not a big deal to make JavaScript strongly typed, but it is not going to happen. So there is no future for TypeScript. It was created by danish guy Anders Hejlsberg, he achieved perfection developing  C# and Borland Delphi with its VCL (Visual Components Library), yes OOP worked well, C#, Delphi they ware technological marvels of their time, but they are useless in distributed systems. That is why we don't code UI in C# anymore.

TypeScript is technological infection.

**Comment by BasicPrimitives** [comment]
"We use a lot of Angular, how do you feel about making a special ng-basic-primitives package?
if we make a pull request for it, will you include it?"

Angular is a Google's project. Google needs to keep its dominance in search. It depends on HTML static content. Absence of "SEO optimized sites" it is death of the Google search. If you look at Microsoft they don't consider Bing as top priority for their business anymore. Search as a business is going away. Finding content over internet using Google becomes more and more problematic. Dynamic web sites, Amazon Store, Games, Mobile applications, Netflix and etc they are all content delivery platforms not depending on Google search anymore. Google created Angular to keep web sites convenient for harvesting data. They deliberately avoided creation of cross platform support like React Native, because it is against of their core business. So as a result Facebook, came with their own cross platform development framework which gained instant popularity. Google is loosing its ground, they are very reactive. They created Chrome to save HTML and avoid Flash and SilverLight to dominate web and kill HTML search. They created Android to kill iPhone and avoid App Store to kill web and so on. They promise Free High Speed Fiber Optic Internet already for last 20 years, without any results. They don't need it. High speed internet will kill HTML and WEB. It will bring Augment Reality UI and virtual communications. Google is only perfect in cleaning negative opinion out of heir search results. So I am going to publish this message for you and remove,

So Angular does not provide required functionality for cross platform development and it actively looses its user base. 

Angular is less than 15% percent of new projects development. It is 3d in line for support. We would like to support Vue first.

**Comment by BasicPrimitives** [comment]
"It doesn't work really well now with typescript / esnext modules ... Tree-shaking isn't possible at all it seems... Making it a > 1MB (minimized, heavy) dep... Any plans for refactoring?
if we make a pull request for it, will you include it?"

1. We don't care about "Tree-shaking" at all.
2. Splitting project into multiple sub projects makes only sense in order to make public MIT core of the project. Only lazy does not write Org Chart nowadays, so probably it makes sense to make core Org Chart functionality for free, so that way all other features are going to be add-ons.

**Comment by BasicPrimitives** [comment]
"Can we make connectors / annotations clickable?"
You can customize Labels with templates. So template can contain code for event handlers bindings.
In order to make lines clickable we need to add API for that.

**Comment by DutchKevv** [comment]
@BasicPrimitives 

Pretty clear answers..

You don't care about typescript (Vue 3 is in typescript), don't care about enterprise (where Angular has a lot bigger share) and don't care about package size.

Thanks for heads up.

**Comment by BasicPrimitives** [comment]
1. I did not say that we don't care about package size. I said that Tree Shaker support is not our objective.

2. Our primary customer is enterprise, majority of sales requests goes from them

3. On Saturdays we receive emails and support requests from various software "Enthusiasts" 

4. I don't know what is going on with Vue, but ReactJs developers use TypeScript pretty frequently as well. I said that it makes sense to support TypeScript. But again, it is not our preference, because ECMA script evolves without looking at TypeScript, so code refactoring into latest ECMA script has higher priority than TypeScript.

5. We cannot promise anything if we don't start right away. You requested 3 major features:

 

Splitting project into multiple sub components, so they can be included separately. - 2 weeks. (It requires major rework of all samples and testing)

Adding TypeScript definitions: 3-5 days

Adding clickable annotations and templates for annotations labels. Most likely it will end-up in major rework of Annotations API. 2 weeks at least. (I take into account that everything already done, so it is not a big deal to implement, 2 weeks it is very safe estimate)

Adding angular support : Conversion of  existing samples into Angular - 1 -2 weeks. (We don't have experience with Angular, so we need to take a look at how its internals work, it is very dirty and overoptimistic estimate)

Adding Angular directive  & Drag&Drop  Support - 1-2 weeks. Most likely ng directive is need, since React does not support D&D for JavaScript controls. It should be native react component which uses React rendering engine, so Angular must have the same issues.

npm package creation and samples publishing at github - add another week to round up everything

 

So it is about  10 weeks in total, so the budget is around 40K USD

Our average sale is 5 dev licenses, so it is 1.7K CAD

 

The only feature which we think to implement it is "click" support for connection lines. We have it in our back log actually. I just cannot promise it to you because we work on other staff at the moment.

Please, don't overreact, but we cannot promise beyond our abilities.

**Comment by DutchKevv** [comment]
Ok ok... Fair enough ;)

It seemed a bit like al could go **** them self with Google and TS shit.

I am happy with the response above! :)

Anyway, back to business.... 👍 

If TS is not 1st prio... How about I make a fork? I can understand this is not the way to go also, so I would 'love' to just send a PR to you, with a *.d.ts. (already created it) in it.. So we can get some Intelli support in IDE's...

Also I do agree about Angular being the 'underdog', but in my experience, it gets used when money is endless .... (energy, banking etc).

So just want to give a helping hand. Maybe even to give customers a feeling its 'all-over-the-place'. The money is there xD

So, lets drop the Angular support for now. Would you care about a *.d.ts file just to make IDE's more happy in TS world?

Once more, I already made them.... So its just a PR... 

It could get outdated, thats a risk, but you get more google/github/etc hits cause it HAS a *.d.ts file.

Reason I do it, is cause I hope more people setup interfaces for your internal js 'API' (looks a bit more PRO if IDE gives 'error' when calling undefined function etc etc ;)

Thanks again

**Comment by DutchKevv** [comment]
Adding angular support : Conversion of  existing samples into Angular - 1 -2 weeks. (We don't have experience with Angular, so we need to take a look at how its internals work, it is very dirty and overoptimistic estimate)''

Angular has a 'hard' way and a 'lazy' way..... I understand its a path again.

How about I make a package, that just includes 'basic-primitives' and nothing else... Angular DEVS can call funcs whenever, but just don't have hints. 

You do make it up to Google search / NPM search / etc, cause you have an ng-* package, thats worth it I guess... ?

**Comment by DutchKevv** [comment]
Imagine when calling primities.*.config, and someone giving a number instead of a string as param, and it gives an error in its IDE... It shows what options are POSSIBLE without digging docs when hovering and shows that a FAM/ORG graph has a minimum of **** options set. 

Thats TS

**Comment by DutchKevv** [comment]
Its 02:40 up here, so lets be fair.

I create a *.d.ts file, maybe an Angular package that has no deps (so you have no future trouble). 

All TS devs (Vue 3, Angular etc) devs feel like  its not a jQuery timelaps plugin cause of the hinting. I get a free licence. 

400 dollar is worth as much as my hours spen on *.d.tst! but I hope more TS / Angular / Vue3 devs pick it up for you.

**Comment by BasicPrimitives** [comment]
OK. Make PR. I promise to take a look. 
We added JSDocs annotations for intelligence support
