### ISSUE TITLE
Behaviour change in isVisible

### ISSUE THREAD

**Issue by TiaxDev** [BasicPrimitives/javascript#98]
Hi,

I've been using an older version of BasicPrimitives (5.9.2).
I've recently tried out the latest version (6.5.1) and the migration went smootly (i just had to replace and refactor my templates due to the 6.0.0 non-backward compatible API changes) until i noticed a small change in the behaviour of the **isVisibile** property (i'm using OrgItemConfig).

With BasicPrimitives 5.9.2, i was able to completely hide some items with that property (**connectors were also hidden**).

<img width="350" alt="stamp001" src="https://user-images.githubusercontent.com/10131307/193788855-a0ccc9c7-89b0-4a84-b544-8966eb1b86ce.PNG"> <img height="240" alt="stamp003" src="https://user-images.githubusercontent.com/10131307/193789702-7d5e3dcc-2d1c-4307-8c02-2c648c16b55b.PNG">

After the update, the behaviour seems to be changed. When i trigger the **isVisible** property on an item, the template is hidden correctly, but its connectors with the parent seems to remain visible.

<img width="430" alt="stamp002" src="https://user-images.githubusercontent.com/10131307/193791327-918cfdb5-aa3a-4f2b-9812-6bb2f7521701.PNG">

According to the [API reference](https://www.basicprimitives.com/reference/orgdiagram#OrgItemConfig), the current behaviour of **isVisible** is correct, due to the fact that my items are actually related to visible parents:

`If false, it makes the item invisible in the layout. If the item has no visible parents, its connections are hidden as well. From the navigation perspective, children of hidden nodes become children of their parents.`

Despite this, the behaviour change is breaking some of my logics and i wasn't able to achieve such layout without completely removing the item from the structure.

Is there a way to achieve the previous behaviour, hiding the item **and its connectors**, without actually removing the item itself from the structure?

Thanks

**Comment by BasicPrimitives** [comment]
What we need to do is to test your data set for leaves having isVisible flag set to false and remove them from dataset. Yes, it is not a big deal, but if you have 5000 nodes and only 500 of them are visible, our control will be slow for no reason. We will scab 5000 nodes and remove 4500 nodes having isVisible set to false, on every update.  Yes, we can do it, but as a result we will make control slower for everybody, because it will perform unnecessary transformation of every update. This issue has no functional value and makes View to step into View Model responsibilities.
